CREATE TABLE [dbo].[UserCart](
	[UserCartID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[FoodID] [int] NULL,
	[Qauntity] [int] NULL,
	[CreatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_UserCart] PRIMARY KEY CLUSTERED 
(
	[UserCartID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO